### ISSUE TITLE
Incorrect file reference in "Getting Started" section

### ISSUE THREAD

**Issue by isobeldaley** [learn-co-curriculum/dsc-scrubbing-our-data-lab#1]
In the "Getting Started" section, the file 'lego_data_merged.csv' should be referenced.  Not 'walmart_data_not_cleaned.csv'

**Comment by sumedh10** [comment]
Fixed [here](https://github.com/learn-co-curriculum/dsc-scrubbing-and-cleaning-data-lab/pull/2/commits/d8e1224b55695c5346c0efa69bf2216bea727304).
